sonar.projectKey=Ivan63-coder_python-project-50
sonar.organization=ivan63-coder-1
sonar.sources=gendiff
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests/test_data/**,tests/__pycache__/**,**/__pycache__/**
sonar.python.xunit.skipDetails=true
