sonar.projectKey=your_github_username_your_project_name
sonar.organization=your_github_username
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=tests/test_data/**
sonar.python.version=3.12